--[[
PE002.lua
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
]]

function fibonacci(n)
  if n<=1 then return 1 end
  --if n<=0 then return 0 end
  return fibo(n-1)+fibo(n-2)
end



fibo1=0
fibo2=1
fibo3=fibo1+fibo2
a=0
while fibo3<4000000 do
  --print(fibo3)
  if fibo3%2==0 then a=a+fibo3 end
  fibo1,fibo2=fibo2,fibo3
  fibo3=fibo1+fibo2
end
print(a)