--[[
PE044.lua
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are
pentagonal and D = |Pk -Pj| is minimised; what is the value of D?
--]]
-- Solution dégueulasse. La première réponse est la bonne.
-- Temps trop long pour arriver jusqu'au bout et prouver que c'est la meilleure.

function P(n)
  return n*(3*n-1)/2
end


function isPenta(n)
  return n==P(math.floor((1+math.sqrt(1+24*n))/6))
end

--[[
for i=1,146 do
  if isPenta(i) then
    print(i)
  end
end

--]]


Dk=math.huge
print(Dk)
i=2
while i<(Dk-1)/3 do
  --print(i)
  for j=1,i-1 do
    --print("--j=",j)
    if isPenta(P(i)-P(j)) and isPenta(P(i)+P(j)) then
      Dk=math.min(Dk,P(i)-P(j))
      print("Dk=",Dk,i,j,"imax=",(Dk-1)/3)
    end
  end
  i=i+1
end
print("-->",Dk)







